apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: characters

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.characters.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.models.storage }}